import Intro from '@/components/Intro';
import Technologies from '@/components/Technologies';
import TransitionEffect from '@/components/menu/TransitionEffect';
import Projects from '@/components/projects/Projects';
import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Jacob Gifford | Home</title>
        <meta name='description' content='generated by create next app' />
      </Head>
      <TransitionEffect />
      <main>
        <Intro />
        <Technologies />
        <span className='w-full flex justify-center'>
          <div className='w-11/12 h-[1px] bg-gray-950 dark:bg-white' />
        </span>
        <Projects />
      </main>
    </>
  );
}
