import * as THREE from 'three';
import { GLTF } from 'three-stdlib';

export type NodeMaterialProps = {
  nodes: Record<string, Record<string, any>> & THREE.Mesh;
  materials: MaterialsDictionary;
};
interface MaterialsDictionary {
  [index: string]: THREE.MeshStandardMaterial | THREE.MeshPhysicalMaterial;
}

export type GLTFResult = GLTF & {
  nodes: {
    Cylinder014: THREE.Mesh;
    Cylinder014_1: THREE.Mesh;
    Cylinder013: THREE.Mesh;
    Cylinder013_1: THREE.Mesh;
    Cube058: THREE.Mesh;
    Cube058_1: THREE.Mesh;
    light1: THREE.Mesh;
    light2: THREE.Mesh;
    Circle: THREE.Mesh;
    water_surface: THREE.Mesh;
    float1: THREE.Mesh;
    float2: THREE.Mesh;
    float5: THREE.Mesh;
    float4: THREE.Mesh;
    float3: THREE.Mesh;
    float6: THREE.Mesh;
    rock2: THREE.Mesh;
    rock4: THREE.Mesh;
    rock1: THREE.Mesh;
    rock2001: THREE.Mesh;
    rock3001: THREE.Mesh;
    rock1001: THREE.Mesh;
    rock4001: THREE.Mesh;
    rock4002: THREE.Mesh;
    rock4003: THREE.Mesh;
    rock3002: THREE.Mesh;
    rock3003: THREE.Mesh;
    rock3006: THREE.Mesh;
    rock4004: THREE.Mesh;
    rock3004: THREE.Mesh;
    rock3005: THREE.Mesh;
    rock4005: THREE.Mesh;
    rock3007: THREE.Mesh;
    rock4006: THREE.Mesh;
    rock4007: THREE.Mesh;
    rock4008: THREE.Mesh;
    rock4009: THREE.Mesh;
    rock4010: THREE.Mesh;
    rock4011: THREE.Mesh;
    rock4012: THREE.Mesh;
    rock3008: THREE.Mesh;
    rock3009: THREE.Mesh;
    rock4013: THREE.Mesh;
    rock4014: THREE.Mesh;
    rock4015: THREE.Mesh;
    rock4016: THREE.Mesh;
    rock4017: THREE.Mesh;
    waterfall: THREE.Mesh;
    Cylinder003: THREE.Mesh;
    Cylinder003_1: THREE.Mesh;
    base: THREE.Mesh;
    base2: THREE.Mesh;
    rope2: THREE.Mesh;
    stand2: THREE.Mesh;
    arm2: THREE.Mesh;
    light_container_2: THREE.Mesh;
    light_container: THREE.Mesh;
    stand: THREE.Mesh;
    arm: THREE.Mesh;
    rope: THREE.Mesh;
    handle: THREE.Mesh;
    head: THREE.Mesh;
    pondWalls: THREE.Mesh;
    dirt: THREE.Mesh;
    crystals: THREE.Mesh;
    grass: THREE.Mesh;
    pond: THREE.Mesh;
    Cylinder004: THREE.Mesh;
    Cylinder004_1: THREE.Mesh;
    Cylinder005: THREE.Mesh;
    Cylinder005_1: THREE.Mesh;
    Cylinder006: THREE.Mesh;
    Cylinder006_1: THREE.Mesh;
    Cylinder007: THREE.Mesh;
    Cylinder007_1: THREE.Mesh;
    Cylinder001: THREE.Mesh;
    Cylinder001_1: THREE.Mesh;
    tree: THREE.Mesh;
    protruding_roots: THREE.Mesh;
    Cylinder002: THREE.Mesh;
    Cylinder002_1: THREE.Mesh;
    Cylinder: THREE.Mesh;
    Cylinder_1: THREE.Mesh;
    Cylinder008: THREE.Mesh;
    Cylinder008_1: THREE.Mesh;
    Cylinder009: THREE.Mesh;
    Cylinder009_1: THREE.Mesh;
  };
  materials: {
    ['staff gold']: THREE.MeshStandardMaterial;
    ['red gemstone']: THREE.MeshStandardMaterial;
    ['staff wood']: THREE.MeshStandardMaterial;
    lampLightEmissive: THREE.MeshStandardMaterial;
    waterfall: THREE.MeshStandardMaterial;
    rocks: THREE.MeshStandardMaterial;
    path: THREE.MeshStandardMaterial;
    dirt: THREE.MeshStandardMaterial;
    lampMetal: THREE.MeshStandardMaterial;
    innerWood: THREE.MeshStandardMaterial;
    fencing1: THREE.MeshStandardMaterial;
    wood: THREE.MeshStandardMaterial;
    axeBite: THREE.MeshStandardMaterial;
    ['blue gemstone']: THREE.MeshPhysicalMaterial;
    grass: THREE.MeshStandardMaterial;
    basin: THREE.MeshStandardMaterial;
    ['tree wood']: THREE.MeshStandardMaterial;
    roots: THREE.MeshStandardMaterial;
    gilding: THREE.MeshStandardMaterial;
    ['axe head base']: THREE.MeshStandardMaterial;
    ['starks axe bite']: THREE.MeshStandardMaterial;
  };
};

export type GLTFNodesMaterials = {
  nodes: {
    Cylinder003: THREE.Mesh;
    Cylinder003_1: THREE.Mesh;
    Cylinder014: THREE.Mesh;
    Cylinder014_1: THREE.Mesh;
    Cylinder013: THREE.Mesh;
    Cylinder013_1: THREE.Mesh;
    waterfall: THREE.Mesh;
    Cube058: THREE.Mesh;
    Cube058_1: THREE.Mesh;
    light1: THREE.Mesh;
    light2: THREE.Mesh;
    Circle: THREE.Mesh;
    water_surface: THREE.Mesh;
    float1: THREE.Mesh;
    float2: THREE.Mesh;
    float5: THREE.Mesh;
    float4: THREE.Mesh;
    float3: THREE.Mesh;
    float6: THREE.Mesh;
    rock2: THREE.Mesh;
    rock4: THREE.Mesh;
    rock1: THREE.Mesh;
    rock2001: THREE.Mesh;
    rock3001: THREE.Mesh;
    rock1001: THREE.Mesh;
    rock4001: THREE.Mesh;
    rock4002: THREE.Mesh;
    rock4003: THREE.Mesh;
    rock3002: THREE.Mesh;
    rock3003: THREE.Mesh;
    rock3006: THREE.Mesh;
    rock4004: THREE.Mesh;
    rock3004: THREE.Mesh;
    rock3005: THREE.Mesh;
    rock4005: THREE.Mesh;
    rock3007: THREE.Mesh;
    rock4006: THREE.Mesh;
    rock4007: THREE.Mesh;
    rock4008: THREE.Mesh;
    rock4009: THREE.Mesh;
    rock4010: THREE.Mesh;
    rock4011: THREE.Mesh;
    rock4012: THREE.Mesh;
    rock3008: THREE.Mesh;
    rock3009: THREE.Mesh;
    rock4013: THREE.Mesh;
    rock4014: THREE.Mesh;
    rock4015: THREE.Mesh;
    rock4016: THREE.Mesh;
    rock4017: THREE.Mesh;
    base: THREE.Mesh;
    base2: THREE.Mesh;
    rope2: THREE.Mesh;
    stand2: THREE.Mesh;
    arm2: THREE.Mesh;
    light_container_2: THREE.Mesh;
    light_container: THREE.Mesh;
    stand: THREE.Mesh;
    arm: THREE.Mesh;
    rope: THREE.Mesh;
    handle: THREE.Mesh;
    head: THREE.Mesh;
    pondWalls: THREE.Mesh;
    dirt: THREE.Mesh;
    crystals: THREE.Mesh;
    grass: THREE.Mesh;
    pond: THREE.Mesh;
    Cylinder004: THREE.Mesh;
    Cylinder004_1: THREE.Mesh;
    Cylinder005: THREE.Mesh;
    Cylinder005_1: THREE.Mesh;
    Cylinder006: THREE.Mesh;
    Cylinder006_1: THREE.Mesh;
    Cylinder007: THREE.Mesh;
    Cylinder007_1: THREE.Mesh;
    Cylinder001: THREE.Mesh;
    Cylinder001_1: THREE.Mesh;
    tree: THREE.Mesh;
    protruding_roots: THREE.Mesh;
    Cylinder002: THREE.Mesh;
    Cylinder002_1: THREE.Mesh;
    Cylinder: THREE.Mesh;
    Cylinder_1: THREE.Mesh;
    Cylinder008: THREE.Mesh;
    Cylinder008_1: THREE.Mesh;
    Cylinder009: THREE.Mesh;
    Cylinder009_1: THREE.Mesh;
  };
  materials: {
    ['staff gold']: THREE.MeshStandardMaterial;
    ['red gemstone']: THREE.MeshStandardMaterial;
    ['staff wood']: THREE.MeshStandardMaterial;
    lampLightEmissive: THREE.MeshStandardMaterial;
    waterfall: THREE.MeshStandardMaterial;
    rocks: THREE.MeshStandardMaterial;
    path: THREE.MeshStandardMaterial;
    dirt: THREE.MeshStandardMaterial;
    lampMetal: THREE.MeshStandardMaterial;
    innerWood: THREE.MeshStandardMaterial;
    fencing1: THREE.MeshStandardMaterial;
    wood: THREE.MeshStandardMaterial;
    axeBite: THREE.MeshStandardMaterial;
    ['blue gemstone']: THREE.MeshPhysicalMaterial;
    grass: THREE.MeshStandardMaterial;
    basin: THREE.MeshStandardMaterial;
    ['tree wood']: THREE.MeshStandardMaterial;
    roots: THREE.MeshStandardMaterial;
    gilding: THREE.MeshStandardMaterial;
    ['axe head base']: THREE.MeshStandardMaterial;
    ['starks axe bite']: THREE.MeshStandardMaterial;
  };
};
